### ISSUE TITLE
Couleur des lignes

### ISSUE THREAD

**Issue by tsoonav** [Jilano5/MMM-Ilevia-Lille#1]
Bonjour,

Tout d'abord bravo pour ce module.
J'avoue avoir déjà pensé à faire ce module mais n'habitant plus sur la métropole je n'ai pas pris le temps de le faire.
Petite suggestion d'amélioration de votre module. Que pensez vous d'afficher le numéro de la ligne de la couleur de la ligne telle que définie par Ilévia : https://opendata.lillemetropole.fr/explore/dataset/ilevia-couleurslignes/table/

Le mieux pour éviter les appels API intempestifs serait que le code couleur de la ligne remonte dans l'appel des prochains horaires.
Je peux m'arranger pour que cette info remonte dans l'API si vous êtes prêt à faire la modif.

Je me permets aussi de vous suggérer de poster votre ré-utilisation en bas de cette page : https://opendata.lillemetropole.fr/explore/dataset/ilevia-prochainspassages/information/?sort=cletri
L'admin de la plateforme MEL Open data que je suis vous remercie ;)
Et à votre dispo pour vous aider à améliorer les données !
Bonne journée
Jérôme

**Comment by Jilano5** [comment]
Bonjour,
Merci à vous de mettre à disposition les données ;)

J'ai pris en compte la modification suggéré (eca339f). Pour la récupération de la couleur, je le fais à l'initialisation du module pour il y aura juste 2-3 appel API de plus. 
Donc pas de modification à faire de votre côté.

N'hésitez pas à tester le module et remonter les éventuelles erreurs. 

J'ai également posté, sur OpenData de la MEL, la réutilisation.

Bonne journée et bon confinement,
Jérémy
