### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by myikeal** [Jilano5/MMM-Ilevia-Lille#2]
Hello, I tried to install the ilevia module but when implementing the code in the config file I get a black screen after restarting the program.
Can you tell me where I went wrong.
Thank you

**Comment by tsoonav** [comment]
hi,

can you send the config you made ?
thanks

**Comment by tsoonav** [comment]
hi,

can you send the config you made ?
thanks

**Comment by myikeal** [comment]
Bonjour, je vous envoie le fichier de configuration.
Merci pour votre temps
[config.js.zip](https://github.com/Jilano5/MMM-Ilevia-Lille/files/5554652/config.js.zip)

**Comment by tsoonav** [comment]
Bonjour, je ne vois pas d'erreur dans la structure du fichier.
Apres pour le sens ligne, il faut mettre une valeur comme indiqué sur le portail open data : 
![image](https://user-images.githubusercontent.com/30594988/99814946-fb150d80-2b49-11eb-93df-252f5e5c8906.png)
donc soit LE PARC, soit MARCQ PISCINE
si vous pouvez prendre les 2 bus, mettez 2 lignes, une fois avec chaque sens, ça devrait marcher. C'est que ce module qui fait planter ?
Apres perso j'avoue que je n'utilise pas le module (nh'abitant pas sur la métropole), par contre je connais la donnée publiée

**Comment by myikeal** [comment]
Bonjour, non même en ajoutant le sens j'obtiens un écran noir.
Que ce soit en mettant le code seul ou en l’intégrant au reste de ma structure le résultat est le même.
Merci d'avoir essayé.

**Comment by Jilano5** [comment]
Si vous essayez ça, ça devrait marcher:
`{nomstation:'DHAINAUT', codeligne:'L5', sensligne:"LE PARC" , color:'blue', icon:'train'}`
Désolé pour la réponse tardive
